Fixed some NPC ID bugs I accidentally introduced
Wohlstand/TheXTech pull request #351
Opened 2022-07-12 18:43 UTC by P-Star7

2022-07-13 21:09 UTC, Wohlstand requested changes

2022-07-13 21:09 UTC, Wohlstand commented on src/npc_id.h
> +
纳尼？ You made the file that contains two copies of self in the same file

2022-07-14 00:45 UTC, LoveBodhi commented on src/npc_id.h
> +
Oh, shucks! Just a duplicate copy...!

2022-07-20 22:40 UTC, Wohlstand commented
This pull request is completely broken, please re-do it from the latest state.

2022-07-20 22:40 UTC, closed without merging